export interface IControls
{
  ProjectTitle:string;
  SubmittedBy:string;
  ProjectType:string;
  PhoneEmail:string;
  TotalBudget:string;
  ProposalDate:string;
  VersionNo:string;
  ProjStatrtDate:string;
  ProjEndDate:string;
  ProjCompletionDate:string;
  ProjectSponsor:string;
  ProjectManager:string;
  StakeholderName:[],
  StakeholderRole:[],
  StkContactInfo:[],
  ProjectSummary:string,
  ProjectObjectives:[],
  BusinessJustification:string,
  CaseFastTrack:string,
  RelatedProjects:string,
  Technology:string,
  RiskOverview:string,
  Inscope:string,
  Outscope:string,
  Deliverables:string,
  TimelineOverview:string,
  Milestone:[],
  Deadline:[],
  StaffingOverview:[],
  StaffingFunction:[],
  CapReq:[],
  FTE:[],
  LineItem:[],
  CapexAmount:[],
  OpexAmount:[],
  TotalAmount:[],
  CapexBudget:[],
  OpexBudget:[],
  GrossBudget:[],
  Function:[],
  Description:[],
  FileLocation:[],
  EdrDate:[],
  EdrApprovedBy:[],
  EdrDecision:[],
  ApproverComments:string
}